"""add language field to recordings table

Revision ID: 3fb71f142905
Revises: 77ee6c6bb633
Create Date: 2025-08-28 19:34:59.938399

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3fb71f142905'
down_revision = '77ee6c6bb633'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # Create the enum type if it doesn't exist
    language_enum = sa.Enum('ENGLISH', 'FRENCH', 'SWAHILI', 'KINYARWANDA', name='languageenum')
    try:
        language_enum.create(op.get_bind())
    except Exception:
        # Enum already exists, that's fine
        pass
    
    # Add column as nullable first  
    op.add_column('recordings', sa.Column('language', language_enum, nullable=True))
    
    # Update existing records to have default language (English)
    op.execute("UPDATE recordings SET language = 'ENGLISH' WHERE language IS NULL")
    
    # Make the column non-nullable
    op.alter_column('recordings', 'language', nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('recordings', 'language')
    # Drop the enum type
    op.execute("DROP TYPE languageenum")
    # ### end Alembic commands ###