"""remove_chief_complaint_column_from_sessions_table

Revision ID: cc8429e20a7d
Revises: 538d817cf3c6
Create Date: 2025-08-26 11:49:20.320785

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cc8429e20a7d'
down_revision = '5f66552e170e'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('sessions', 'chief_complaint')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('sessions', sa.Column('chief_complaint', sa.VARCHAR(length=500), autoincrement=False, nullable=True))
    # ### end Alembic commands ###